//
//  main.c
//  rtb
//
//  Created by Elf Sundae on 7/17/11.
//  Copyright 2011 http://www.0x123.com . All rights reserved.
//

#include <stdio.h>
#include <ctype.h>

#define COLS                12
#define MAX_FILENAME		128


static void printUsage(const char *exeName)
{
	printf("\n\t%s is a command line tool which generate pure C-Style array from\n"
	       "any resource file. FYI: http://www.0x123.com\n"
	       "\tv0.1 Created by Elf Sundae on 7/17/11. Compiled & Tested on Max OS X,\n"
	       "used for Cocoa and iOS development.\n",
	       exeName);
	printf("\nUsage:\n");
	printf("\t\t%s <input file>\n", exeName);
	printf("e.g.\n");
	printf("\t\t./%s image.png > image_png.h\n\n", exeName);	
	
}


int main (int argc, const char * argv[])
{
	char *exeName, *exeNameTemp;
	FILE *fp, *fpo = stdout; 
	int i, ch;
	int p; // length variable
	long length = -1;
	
	/* print usage */
	exeName = (char *)argv[0];
	for (exeNameTemp = exeName; *exeNameTemp; )
	{
		if (*exeNameTemp++ == '/')
			exeName = exeNameTemp;
	}
	if (argc != 2)
	{
		printUsage(exeName);
		return 1;
	}
	
	/* hand input file */
	if ((fp = fopen(argv[1], "r")) == NULL)
	{
		printf("Error opening file \'%s\' !\n", argv[1]);
		return 2;
	}
	
	/* output */
	
	// check if the file name starts with digit number
	fprintf(fpo, "\n\nunsigned char %s", isdigit(argv[1][0]) ? "__" : "");
	// set the variable name for bytes array
	for (i = 0; (ch = argv[1][i]) != 0; i++)
	{
		putc(isalnum(ch) ? ch : '_', fpo);
	}
	fputs("[] = {\n", fpo);
	
	for (p = 0; (length < 0 || p < length) && (ch = getc(fp)) != EOF; p++)
	{
		char *c = p ? ",\n  " : "  ";		
		fprintf(fpo, "%s0x%02x", (p % COLS) ? ", " : c, ch);
	}
    
	
	if (p)
		fputs("\n};\n", fpo);
	
	
	fprintf(fpo, "unsigned int %s", isdigit(argv[1][0]) ? "__" : "");
	for (i = 0; (ch = argv[1][i]) != 0; i++)
		putc(isalnum(ch) ? ch : '_', fpo);
	fprintf(fpo, "_len = %d;\n", p);
	
	fprintf(fpo, "/*** Generated by rtb, http://www.0x123.com ***/\n\n");
	fclose(fp);
	fclose(fpo);
	return 0;
	
}

